---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textinput
  name: textinput-1
spec:
  selector:
    matchLabels:
      app: textinput
  replicas: 1
  template:
    metadata:
      labels:
        app: textinput
    spec:
      containers:
      - image:  registry.cn-hangzhou.aliyuncs.com/text-mqtt/mqtt-text-input:v0.1.0
        name: textinput-dome1
        ports:
        - containerPort: 1883
        command: ["python","main.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textstats
    env: stats
  name: textstats-1
spec:
  selector:
    matchLabels:
      app: textstats
      env: stats
  replicas: 1
  template:
    metadata:
      labels:
        app: textstats
        env: stats
    spec:
      containers:
      - image:  registry.cn-hangzhou.aliyuncs.com/text-mqtt/mqtt-text-stats:v0.1.0
        name: textstats-dome1
        ports:
        - containerPort: 1883
        command: ["python","main.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textsort
    env: sort
  name: textsort-1
spec:
  selector:
    matchLabels:
      app: textsort
      env: sort
  replicas: 1
  template:
    metadata:
      labels:
        app: textsort
        env: sort
    spec:
      containers:
      - image:  registry.cn-hangzhou.aliyuncs.com/text-mqtt/mqtt-text-sort:v0.1.0
        name: textsort-dome1
        ports:
        - containerPort: 1883
        command: ["python","main.py"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textoutput
    env: output
  name: textoutput-1
spec:
  selector:
    matchLabels:
      app: textoutput
      env: output
  replicas: 1
  template:
    metadata:
      labels:
        app: textoutput
        env: output
    spec:
      containers:
      - image:  registry.cn-hangzhou.aliyuncs.com/text-mqtt/mqtt-text-output:v0.1.1
        name: textoutput-dome1
        ports:
        - containerPort: 1883
        command: ["python","main.py"]
