---
apiVersion: v1
kind: Service
metadata:
  name: iiip-redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32211
    name: redisport
  selector:
    place: piworknode002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiip-redis 
    #  namespace: mqtt
  labels:
    place: piworknode002
spec:
  selector:
    matchLabels:
      place: piworknode002
  replicas: 1
  template:
    metadata:
      labels:
        place: piworknode002
    spec:
      nodeName: piworknode002
      containers:
        - name: redis-2
          image: redis
          ports:
            - containerPort: 6379 
