{
 "title": "pv",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "光伏温度",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "ZREVRANGE test/pvinfer/temperature/string 0 0",
     "type": "cli"
    }
   ]
  },
  {
   "title": "光伏光照",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "ZREVRANGE test/pvinfer/irradiance/string 0 0",
     "type": "cli"
    }
   ]
  },
  {
   "title": "故障结果",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "ZREVRANGE test/pvinfer/status/string 0 0",
     "streamingDataType": "TimeSeries",
     "streamingInterval": 1000,
     "type": "cli"
    }
   ]
  }
 ]
}